### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by mariorossi77** [dongy7/twitch-chat-cli#5]
the executable is in conflict with the core package iproute2 '/usr/bin/tc' (traffic control).
Installation fails

**Comment by NotAFile** [comment]
yes, this is very unfortunate... This is a program installed by default on most linux computers.

**Comment by markroxor** [comment]
use -  
```
npx tc
```
instead of
```
tc
```

thank me later

**Comment by mariorossi77** [comment]
> use -
> 
> ```
> npx tc
> ```
> 
> instead of
> 
> ```
> tc
> ```
> 
> thank me later


how am i supposed to run it if the installation fails??
closing this as "won't fix"
